### ISSUE TITLE
Switch to new GitHub Actions based Pages Workflow

### ISSUE THREAD

**Issue by captn3m0** [BlrChessClub/BCC-website#104]
Some of the new SASS changes were breaking on the GitHub Pages version of Jekyll, so I switched to a GitHub Actions based runner, which is working fine.

But now there's two builds running, one of which fails.

We need to switch the Pages setting for this repo to GitHub Actions from the Legacy one. Instructions are documented at https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

Instructions for @BlrChessClub :

1. Go to https://github.com/BlrChessClub/BCC-website/settings/pages
2. Click the Source dropdown
3. Change it to "GitHub Actions"

This will disable the legacy build.

**Comment by BlrChessClub** [comment]
Setting are updated now
