### ISSUE TITLE
Create a Calendar Feed for users to subscribe to

### ISSUE THREAD

**Issue by captn3m0** [BlrChessClub/BCC-website#112]
A calendar that chess lovers can subscribe to to get notified of new events in their own app (such as Google or Apple Calendar) would be nice.

**Comment by BlrChessClub** [comment]
Mobile Layout needs to be fixed for calender:

<img width="164" alt="image" src="https://github.com/user-attachments/assets/fd7d6601-959b-4669-add8-918fd6bdd8f0">

**Comment by captn3m0** [comment]
Also broken on the all events page:

![image](https://github.com/user-attachments/assets/6fee8867-f9a3-44ca-8420-11eed5947f89)

**Comment by captn3m0** [comment]
Pushed a fix, seems okay now.
